apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: codefresh-provider-secret
type: Opaque
data:
# credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: codefresh.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: codefresh
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: codefresh-provider-secret
      key: credentials
